SchoolApp-arif-9/SchoolApp/Models/Section.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SchoolApp.Models
{
    public class Section
    {
        public int SectionId { get; set; }
        public string SectionName { get; set; }
        public int SchoolId { get; set; }
    }
}

SchoolApp-arif-9/SchoolApp/Controllers/SectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolApp.Models;
using SchoolApp.Models.DbGateway;

namespace SchoolApp.Controllers
{
    public class SectionController : Controller
    {
        //
        // GET: /Section/
        SectionDbGateway aSectionDbGateway = new SectionDbGateway();
        public ActionResult Section()
        {
            int schoolid = Convert.ToInt32(Session["school_id2133"]);
            List<Section> sectionList = new List<Section>();
            sectionList = GetSectionList(schoolid);
            ViewBag.SectionList = sectionList;
            return View();
        }

        private List<Section> GetSectionList(int schoolid)
        {
            List<Section> sectionList = aSectionDbGateway.GetAllSection(schoolid);
            return sectionList;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Section(Section aSection)
        {
            if (Session["user_id2133"] == null && Session["userlevel301"] == null)
            {
                return RedirectToAction("Index", "Main");
            }
            else
            {
                aSection.SchoolId = Convert.ToInt32(Session["school_id2133"]);
                List<Section> sectionList = new List<Section>();
                sectionList = GetSectionList(aSection.SchoolId);
                ViewBag.SectionList = sectionList;
                string sectionSave = aSectionDbGateway.SaveSection(aSection);
                ViewBag.SaveSection = sectionSave;
                return View();
            }
        }

        public ActionResult EditSection(int? secid)
        {
         
            int SectionId = Convert.ToInt32(secid);
            Section aSection = new Section();
            aSection = aSectionDbGateway.GetSpecificSection(SectionId);
            ViewBag.EditSectionInfo = aSection;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateSection(Section aSection)
        {
            if (Session["user_id2133"] == null && Session["userlevel301"] == null)
            {
                return RedirectToAction("Index", "Main");
            }
            else
            {
                if (aSection != null)
                {
                  string  sucessAlert = aSectionDbGateway.UpdateSection(aSection);
                  ViewBag.SuccessAlert = sucessAlert;
                  return View();
                }

                return View();
            }
        }

        public JsonResult GetTheSection(int classid, int schoolid)
        {
            SectionDbGateway aSectionDbGateway = new SectionDbGateway();
            int schoolId = Convert.ToInt32(schoolid);
            int classId = Convert.ToInt32(classid);
            List<Section> sectionList = new List<Section>();
            sectionList = aSectionDbGateway.GetTheSection(classid, schoolid);
            if (sectionList != null)
            {
                return Json(sectionList, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }

        }
	}
}

SchoolApp-arif-9/SchoolApp/Views/Section/EditSection.cshtml
@using SchoolApp.Models
@model SchoolApp.Models.Section

@{
    ViewBag.Title = "EditSection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Section</h2>

<div class="row">

    <div class="col-md-12 col-lg-12">
        <section class="panel">
          
            <div class="panel-body">
                <div class="tab-content">
                        <div class="panel-body">
                            @using (Html.BeginForm("UpdateSection", "Section", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
                            {
                                Section aSection = (Section)ViewBag.EditSectionInfo;
                                <div class="form-horizontal" role="form">
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.SectionName, new { @class = "col-md-2 control-label" })
                                        <div class="col-lg-5">
                                            @Html.TextBoxFor(m => m.SectionName, new { @class = "form-control", @Value = aSection.SectionName })
                                            @Html.ValidationMessageFor(model => model.SectionName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="hidden">
                                        @Html.LabelFor(m => m.SectionId, new { @class = "col-md-2 control-label" })
                                        <div class="col-lg-5">
                                            @Html.TextBoxFor(m => m.SectionId, new { @class = "form-control", @Value = aSection.SectionId })
                                            @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <input type="submit" name="submit" value="submit" class="btn btn-primary" />
                                </div>
                            }
                            <div class="col-lg-8">@ViewBag.SaveSection</div>
                        </div>
                   
                </div>
            </div>
        </section>
    </div>
</div>

SchoolApp-arif-9/SchoolApp/Views/Section/Section.cshtml
@using SchoolApp.Models
@model SchoolApp.Models.Section

@{
    ViewBag.Title = "Section";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">

    <div class="col-md-12 col-lg-12">
        <section class="panel">
            <header class="panel-heading tab-bg-dark-navy-blue ">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a data-toggle="tab" href="#home">Section List</a>
                    </li>
                    <li class="">
                        <a data-toggle="tab" href="#about">Add New Section</a>
                    </li>
                </ul>
            </header>
            <div class="panel-body">
                <div class="tab-content">
                    <div id="home" class="tab-pane active">
                        <table class="table table-bordered">
                            <tr class="success"><td>Section Name</td><td>Action</td></tr>
                            @{
                                List<Section> sectionList = new List<Section>();
                                sectionList = (List<Section>) ViewBag.SectionList;
                                foreach (Section aSection in sectionList)
                                {
                                    <tr><td><h5>@aSection.SectionName</h5></td><td><a href="@Url.Action("EditSection", "Section", new{secid=@aSection.SectionId})" class="btn btn-default">Edit</a></td></tr>
                                }
                            }
                        </table>
                        @ViewBag.SaveSection
                    </div>
                    <div id="about" class="tab-pane">
                        <header class="panel-heading">
                            Add New Class
                        </header>
                        <div class="panel-body">
                            @using (Html.BeginForm("Section", "Section", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
                            {
                                <div class="form-horizontal" role="form">
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.SectionName, new { @class = "col-md-2 control-label" })
                                        <div class="col-lg-5">
                                            @Html.TextBoxFor(m => m.SectionName, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.SectionName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <input type="submit" name="submit" value="submit" class="btn btn-primary" />
                                </div>
                            }
                            <div class="col-lg-8">@ViewBag.SaveSection</div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

SchoolApp-arif-9/SchoolApp/Views/Section/UpdateSection.cshtml
@model SchoolApp.Models.Section

@{
    ViewBag.Title = "UpdateSection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.SuccessAlert</h1>

<meta http-equiv="REFRESH" content="2; url=/Section/Section">